/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "CancelCart": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "ClientsBroker": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "FinishCart": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "OrderCart": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "ProductsBroker": {
      "type": "sst.aws.Queue"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}