/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "CartBroker-0543027b-7074-4d83-9eb3-3bbdbdfd6856": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "CartBroker-09c4ea3f-f5bb-4326-a1ad-563640e09432": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "CartBroker-7f4a742c-f6d1-43b7-bbf3-3a77929060ca": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "CartBroker-c2d27d7a-1c04-451b-b7f9-548f2faf3bd3": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "CartBroker-c7c919ea-ad06-448d-947d-da9cb51de85c": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "ClientsBroker": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "FinishCart": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "ProductsBroker": {
      "type": "sst.aws.Queue"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}